[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ksef2.0_python"
version = "0.0.1"
dependencies = [
  "requests",
  "cryptography"
]
requires-python = ">=3.11"
authors = [
  {name = "Stanis≈Çaw Bartkowski", email = "stanislawbartkowski@gmail.com"},
]
readme = "README.md"